spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/meteoservice
  kafka:
    bootstrap-servers: kafka:29092
server:
  port: 8080
kafka:
  topic: my-Topic
  consumer:
    group-id: my-group-id
    client-id: consumer-my-group-id-1
# Open Meteo API configuration
openmeteo:
  api:
    url: https://api.open-meteo.com/v1/forecast
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    root: INFO