spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/meteo
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080
kafka:
  topic: my-Topic
# Open Meteo API configuration
openmeteo:
  api:
    url: https://api.open-meteo.com/v1/forecast
