spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/meteoservice
  kafka:
    bootstrap-servers: kafka:9092
server:
  port: 8080
kafka:
  topic: my-Topic
# Open Meteo API configuration
openmeteo:
  api:
    url: https://api.open-meteo.com/v1/forecast
springdoc:
  swagger-ui:
    path: /swagger-ui.html
resilience4j:
  ratelimiter:
    instances:
      temperatureController:
        limitForPeriod: 10 # Número máximo de solicitudes permitidas por segundo
        limitRefreshPeriod: 1s # Periodo de actualización del límite
        timeoutDuration: 500ms # Tiempo máximo de espera para la siguiente solicitud

    