name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      # Change to the correct directory before running Maven commands
      - name: Navigate to 'code' directory
        run: cd code

      - name: Build with Maven
        run: mvn -B package --file code/pom.xml
      
      # Optional: Upload the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
        working-directory: code
      
      # Upload the built JAR or any other artifacts to GitHub
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.1
        with:
          name: maven-build-artifacts
          path: code/target/*.jar
          if-no-files-found: error
